# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-28 12:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u57ce\u5e02')),
                ('description', models.CharField(max_length=200, verbose_name='\u63cf\u8ff0')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u57ce\u5e02',
                'verbose_name_plural': '\u57ce\u5e02',
            },
        ),
        migrations.CreateModel(
            name='CourseOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u673a\u6784\u540d\u79f0')),
                ('description', models.TextField(verbose_name='\u63cf\u8ff0')),
                ('course_category', models.CharField(choices=[('edu_org', '\u57f9\u8bad\u673a\u6784'), ('teacher', '\u8001\u5e08'), ('other', '\u5176\u4ed6')], default='edu_org', max_length=20, verbose_name='\u673a\u6784\u7c7b\u522b')),
                ('click_number', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6b21\u6570')),
                ('favorite_number', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6570')),
                ('image', models.ImageField(upload_to='org/%Y/%m', verbose_name='\u673a\u6784\u5934\u50cf')),
                ('address', models.CharField(max_length=150, verbose_name='\u673a\u6784\u5730\u5740')),
                ('join_number', models.IntegerField(default=0, verbose_name='\u5b66\u4e60\u4eba\u6570')),
                ('lesson_number', models.IntegerField(default=0, verbose_name='\u8bfe\u7a0b\u6570')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u65f6\u95f4')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CityDict', verbose_name='\u57ce\u5e02')),
            ],
            options={
                'verbose_name': '\u8bfe\u7a0b\u673a\u6784',
                'verbose_name_plural': '\u8bfe\u7a0b\u673a\u6784',
            },
        ),
    ]
