# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-20 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0002_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='course_category',
            field=models.CharField(choices=[('edu_org', '\u57f9\u8bad\u673a\u6784'), ('teacher', '\u9ad8\u6821'),
                                            ('other', '\u4e2a\u4eba')], default='edu_org', max_length=20,
                                   verbose_name='\u673a\u6784\u7c7b\u522b'),
        ),
    ]
