# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-20 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0003_auto_20170320_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='', upload_to='org/%Y/%m', verbose_name='\u8bb2\u5e08\u5934\u50cf'),
        ),
    ]
